const SecondaryAction =  [
    {   id:1,
        name: 'App Store',
        icon: 'appStore',
        placeholder: 'https://apps.apple.com/in/app/appname/id',
        value: null,
        color: '#cbd5e1',
        label: 'App Store developer/app URL'
    },
    {   id:2,
        name: 'ArtStation',
        icon: 'artStation',
        href: 'https://www.artstation.com/',
        placeholder: 'username',
        value: null,
        color: '#171717',
        label: 'ArtStation username'
    },
    {   id:3,
        name: 'behance',
        icon:"behance",
        href: 'https://behance.net/',
        placeholder: 'username',
        value: null,
        color: '#1769ff',
        label: 'Behance profile URL'
    },
    {   id:4,
        name: 'Buy me a coffee',
        icon: 'buyMeACoffee',
        href: 'https://www.buymeacoffee.com/',
        placeholder: 'username',
        value: null,
        color: '#ffdd00',
        light: 1,
        label: 'Buy me a coffee username'
    },
    {   id:5,
        name: 'Cash App',
        icon: 'cashApp',
        href: 'https://cash.app/',
        placeholder: '$username',
        value: null,
        color: '#fff',
        light: 1,
        label: 'Cash App username'
    },
    {   id:6,
        name: 'codeberg',
        icon: 'codeberg',
        href: 'https://codeberg.org/',
        placeholder: 'username',
        value: null,
        color: '#2185d0',
        label: 'Codeberg profile URL'
    },
    {   id:7,
        name: 'diaspora',
        icon: 'diaspora',
        placeholder: 'https://diaspora.social/username',
        value: null,
        color: '#000000',
        label: 'Diaspora profile URL'
    },
    {   id:8,
        name: 'discord',
        icon: 'discord',
        placeholder: 'https://discord.gg/invitecode',
        value: null,
        color: '#7289da',
        label: 'Discord profile URL'
    },
    {   id:9,
        name: 'dribble',
        icon: 'dribble',
        href: 'https://dribbble.com/',
        placeholder: 'username',
        value: null,
        color: '#ea4c89',
        label: 'Dribbble profile URL'
    },
    {   id:10,
        name: 'facebook',
        icon: 'facebook',
        href: 'https://facebook.com/',
        placeholder: 'username or pagename',
        value: null,
        color: '#1877f2',
        label: 'Facebook page URL'
    },
    {   id:11,
        name: 'friendica',
        icon: 'friendica',
        placeholder: 'https://friendica.social/username',
        value: null,
        color: '#1d6e9a',
        label: 'Friendica profile URL'
    },
    {   id:12,
        name: 'funkwhale',
        icon: 'funkwhale',
        placeholder: 'https://funkwhale.audio/username',
        value: null,
        color: '#ffffff',
        label: 'Funkwhale profile URL'
    },
    {   id:13,
        name: 'github',
        icon: 'github',
        href: 'https://github.com/',
        placeholder: 'username',
        value: null,
        color: '#333',
        label: 'Github profile URL'
    },
    {   id:14,
        name: 'gitlab',
        icon: 'gitlab',
        href: 'https://gitlab.com/',
        placeholder: 'username',
        value: null,
        color: '#554488 ',
        label: 'Gitlab profile URL'
    },
    {   id:15,
        name: 'instagram',
        icon: 'instagram',
        href: 'https://instagram.com/',
        placeholder: 'username',
        value: null,
        color: '#405de6',
        // color: '#ffffff',
        label: 'Instagram profile URL'
    },
    {   id:16,
        name: 'linkedIn',
        icon: 'linkedIn',
        href: 'https://linkedin.com/',
        placeholder: 'in/username or company/companyname',
        value: null,
        color: '#0077b5',
        label: 'Linkedin profile URL'
    },
    {   id:17,
        name: 'mastodon',
        icon: 'mastodon',
        placeholder: 'https://mastodon.social/@username',
        value: null,
        color: '#2b90d9',
        label: 'Mastodon profile URL'
    },
    {   id:18,
        name: 'medium',
        icon: 'medium',
        placeholder: 'https://medium.com/publication_name',
        value: null,
        color: '#000000',
        label: 'Medium publication'
    },
    {   id:19,
        name: 'open-collective',
        icon: 'openCollective',
        href: 'https://opencollective.com/',
        placeholder: 'projectname',
        value: null,
        color: '#fff',
        label: 'Open Collective URL'
    },
    {   id:20,
        name: 'patreon',
        icon: 'patreon',
        href: 'https://patreon.com/',
        placeholder: 'username',
        value: null,
        color: '#FF424D',
        label: 'Patreon URL'
    },
    {   id:21,
        name: 'paypal',
        icon: 'paypal',
        href: 'https://paypal.me/',
        placeholder: 'username',
        value: null,
        color: '#003087',
        label: 'PayPal.me URL'
    },
    {   id:22,
        name: 'peertube',
        icon: 'peertube',
        placeholder: 'https://peertube.video/channelname',
        value: null,
        color: '#ffffff',
        label: 'Peertube channel URL'
    },
    {   id:23,
        name: 'pinterest',
        icon: 'pinterest',
        href: 'https://pinterest.com/',
        placeholder: 'username',
        value: null,
        color: '#bd081c',
        label: 'Pinterest profile URL'
    },
    {   id:24,
        name: 'pixelfed',
        icon: 'pixelfed',
        placeholder: 'https://pixelfed.social/username',
        value: null,
        color: '#8d59a8',
        label: 'Pixelfed profile URL'
    },
    {   id:25,
        name: 'Play Store',
        icon: 'playStore',
        placeholder: 'https://play.google.com/store/apps/details?id=',
        value: null,
        color: '#fff',
        light: 1,
        label: 'Play Store developer/app URL'
    },
    {   id:26,
        name: 'quora',
        icon: 'quora',
        href: 'https://quora.com/',
        placeholder: 'username',
        value: null,
        color: '#a82400',
        label: 'Quora profile URL'
    },
    {   id:27,
        name: 'reddit',
        icon: 'reddit',
        href: 'https://reddit.com/',
        placeholder: 'username',
        value: null,
        color: '#ff5700',
        label: 'Reddit profile URL'
    },
    {   id:28,
        name: 'Siilo',
        icon: 'siilo',
        href: 'https://app.siilo.com/qr/',
        placeholder: 'userid',
        value: null,
        color: '#17233b',
        label: 'Siilo userid'
    },
    {   id:29,
        name: 'snapchat',
        icon: 'snapchat',
        placeholder: 'https://snapchat.com/username',
        value: null,
        color: '#fffc00',
        label: 'Snapchat profile URL'
    },
    {   id:30,
        name: 'soundcloud',
        icon: 'soundcloud',
        placeholder: 'https://soundcloud.com/username',
        value: null,
        color: '#ff3300',
        label: 'Soundcloud profile URL'
    },
    {   id:31,
        name: 'spotify', 
        icon: 'spotify', 
        placeholder: 'https://spotify.com/username',
        value: null,
        color: '#1ed760',
        label: 'Spotify profile URL'
    },
    {   id:32,
        name: 'TikTok',
        icon: 'tiktok',
        href: 'https://tiktok.com/',
        placeholder: 'username',
        value: null,
        color: '#fff',
        label: 'TikTok profile URL'
    },
    {   id:33,
        name: 'tumblr',
        icon: 'tumblr',
        value: null,
        color: '#2c4762',
        href: 'https://',
        hrefEnd: '.tumblr.com/',
        placeholder: 'username',
        label: 'Tumblr blog URL'
    },
    {   id:34,
        name: 'twitch',
        icon: 'twitch',
        href: 'https://twitch.tv/',
        placeholder: 'username',
        value: null,
        color: '#9146ff',
        label: 'Twitch profile URL'
    },
    {   id:35,
        name: 'twitter',
        icon: 'twitter',
        href: 'https://twitter.com/',
        placeholder: 'username',
        value: null,
        color: '#1da1f2',
        label: 'Twitter profile URL'
    },
    {   id:36,
        name: 'vimeo',
        icon: 'vimeo',
        href: 'https://vimeo.com/',
        placeholder: 'channelname',
        value: null,
        color: '#1ab7ea',
        label: 'Vimeo channel URL'
    },
    {   id:37,
        name: 'vk',
        icon: 'vk',
        href: 'https://vk.com/',
        placeholder: 'pagename',
        value: null,
        color: '#4a76a8',
        label: 'VK page URL'
    },
    {   id:38,
        name: 'yelp',
        icon: 'yelp',
        href: 'https://yelp.com/',
        placeholder: 'bizname',
        value: null,
        color: '#fff',
        label: 'Yelp page URL'
    },
    {   id:39,
        name: 'youtube',
        icon: 'youtube',
        href: 'https://youtube.com/',
        placeholder: 'channel name or ID',
        value: null,
        color: '#ff0000',
        label: 'Youtube channel URL'
    }
]

export default SecondaryAction